name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v3.0.2 # https://github.com/marketplace/actions/nix-shell
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        packages: gn,findutils,xz,tree
        # Disclaimer: wow I really have no idea what's happening with this gn and gclient thing
        script: |
          set -x || true
          GIT_ROOT=$(pwd)
          cd /tmp
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ./depot_tools
          export PATH=$(realpath ./depot_tools):$PATH
          gclient root
          gclient config --spec 'solutions = [
            {
              "name": "devtools-frontend",
              "url": "https://chromium.googlesource.com/devtools/devtools-frontend.git",
              "deps_file": "DEPS",
              "managed": False,
              "custom_deps": {},
            },
          ]
          '
          git clone $GIT_ROOT devtools-frontend/
          cd devtools-frontend/
          gclient sync || true
          gn gen out/build --args='devtools_skip_typecheck=true'
          autoninja -C out/build/
          tree out/build

    - name: Archive All
      uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657 # https://github.com/marketplace/actions/zip-release
      with:
        type: 'zip'
        filename: 'all.zip'
    - name: Archive Release
      uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657 # https://github.com/marketplace/actions/zip-release
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'out/fast-build'
    - name: Upload Release
      if: always()
      uses: ncipollo/release-action@v1.10.0 # https://github.com/marketplace/actions/create-release
      with:
        artifacts: "*.zip"
        omitBody: true
        prerelease: true
        tag: ${{ github.sha }}
        body: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
