name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v3.0.2 # https://github.com/marketplace/actions/nix-shell
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        packages: gn
        script: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /opt/depot_tools
          export PATH=$(realpath /opt/depot_tools):$PATH
          gn gen out/fast-build --args='devtools_skip_typecheck=true'; autoninja -C out/fast-build/

    - name: Archive Release
      uses: thedoctor0/zip-release@main # https://github.com/marketplace/actions/zip-release
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'out/fast-build/'
